github_checks:
  annotations: false

coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 100%
#        informational: true
    patch:
      default:
        target: 0%
        threshold: 100%
#        informational: true
